version: "3.8"

services:
  app:
    build: .
    ports:
      - "9808:9808"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
